apiVersion: networking.k8s/vbeta1
kind: GateWay
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: rubblestech.com
    http:
      paths:
        - path: /
          backend:
            serviceName: client-cluster-ip-service
            servicePort: 3001  
        
        - pathType: Prefix
          path: /api/
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5001